sudo: required
services:
  - docker

before_install:
  - docker build -t franzu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true franzu/react-test npm run test

after_succes:
  - docker build -t franzu/multi-client ./client
  - docker build -t franzu/multi-nginx ./nginx
  - docker build -t franzu/multi-server ./server
  - docker build -t franzu/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push franzu/multi-client
  - docker push franzu/multi-nginx
  - docker push franzu/multi-server
  - docker push franzu/multi-worker